rootProject.name = "snitch"
include("core", "tests", "gsonparser", "undertow")
include("example")
include("bootstrap")
include("coroutines")
include("types")
include("validation")
include("shank")
include("auth")
include("exposed")
include("exposed-h2")
include("exposed-postgres")
